### ISSUE TITLE
is not a quiz

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/js-basics-javascript-basics-quiz#1]

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
