### ISSUE TITLE
Mislabeled lesson?

### ISSUE THREAD

**Issue by bkhartmire** [learn-co-curriculum/js-basics-javascript-basics-quiz#2]
This lesson is labeled JavaScript Basics Quiz but it is showing up as an exact copy of the Variables readme that was already covered. Perhaps this is only an issue with my account?

**Comment by vanetoro** [comment]
Yea same thing just happened to me!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
